In [1]:
import pandas as pd
import numpy as np

#### Load the data

In [2]:
data_preprocessed = pd.read_csv('PredictTheAbsentPreprocessed.csv')

In [3]:
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  
0               30          0         2     1                          4  
1               31          0         1     0                          0  
2               31          0         0     0                          2  
3               24          0         2     0                          4  
4               30          0         2     1                          2

#### Create the targets

In [4]:
data_preprocessed['Absenteeism Time in Hours'].median()

3.0

In [5]:
#np.where(condition, value if true, value if false)
#this also balances our dataset
targets = np.where(data_preprocessed['Absenteeism Time in Hours'] > 
                   data_preprocessed['Absenteeism Time in Hours'].median(), 1, 0)

In [6]:
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [7]:
data_preprocessed['Excessive Absenteeism'] = targets

In [8]:
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  \
0               30          0         2     1                          4   
1               31          0         1     0                          0   
2               31          0         0     0                          2   
3               24          0         2     0                          4   
4               30          0         2     1                          2   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

#### A comment on the targets

In [9]:
#checking the balance of our dataset
targets.sum()/targets.shape[0]

0.45571428571428574

In [10]:
data_with_targets = data_preprocessed.drop(['Absenteeism Time in Hours', 'Day of the week', 'Daily Work Load Average', 'Distance to Work'], axis=1)

In [11]:
data_with_targets is data_preprocessed

False

In [12]:
data_with_targets.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0         0         0         0         1            7   
1         0         0         0         0            7   
2         0         0         0         1            7   
3         1         0         0         0            7   
4         0         0         0         1            7   

   Transportation Expense  Age  Body Mass Index  Education  Children  Pets  \
0                     289   33               30          0         2     1   
1                     118   50               31          0         1     0   
2                     179   38               31          0         0     0   
3                     279   39               24          0         2     0   
4                     289   33               30          0         2     1   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

#### Select the inputs for the regression

In [13]:
data_with_targets.shape

(700, 12)

In [14]:
# DataFrame.iloc[row indices, column indices]
#data_with_targets.iloc[:, :14]
data_with_targets.iloc[:, :-1]

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0           0         0         0         1            7   
1           0         0         0         0            7   
2           0         0         0         1            7   
3           1         0         0         0            7   
4           0         0         0         1            7   
..        ...       ...       ...       ...          ...   
695         1         0         0         0            5   
696         1         0         0         0            5   
697         1         0         0         0            5   
698         0         0         0         1            5   
699         0         0         0         1            5   

     Transportation Expense  Age  Body Mass Index  Education  Children  Pets  
0                       289   33               30          0         2     1  
1                       118   50               31          0         1     0  
2                       179   38               31          0         0     0  
3                       279   39               24          0         2     0  
4                       289   33               30          0         2     1  
..                      ...  ...              ...        ...       ...   ...  
695                     179   40               22          1         2     0  
696                     225   28               24          0         1     2  
697                     330   28               25          1         0     0  
698                     235   32               25          1         0     0  
699                     291   40               25          0         1     1  

[700 rows x 11 columns]

In [15]:
unscaled_inputs = data_with_targets.iloc[:, :-1]

#### Standardize the data

In [16]:
#from sklearn.preprocessing import StandardScaler

#absenteeism_scalar = StandardScaler()

In [17]:
# import the libraries needed to create the Custom Scaler
# note that all of them are a part of the sklearn package
# moreover, one of them is actually the StandardScaler module, 
# so you can imagine that the Custom Scaler is build on it

# Custom Scaler built to standardize only the numerical variables and not dummies

from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.preprocessing import StandardScaler

# create the Custom Scaler class

class CustomScaler(BaseEstimator,TransformerMixin): 
    
    # init or what information we need to declare a CustomScaler object
    # and what is calculated/declared as we do
    
    def __init__(self,columns,copy=True,with_mean=True,with_std=True):
        # with some columns 'twist'
        self.columns = columns
        self.copy = copy
        self.with_mean = with_mean
        self.with_std = with_std
        # scaler is nothing but a Standard Scaler object
        self.scaler = StandardScaler(copy = copy,with_mean = with_mean, with_std = with_std)
        self.mean_ = None
        self.var_ = None
        
    
    # the fit method, which, again based on StandardScale
    
    def fit(self, X, y=None):
        self.scaler.fit(X[self.columns], y)
        self.mean_ = np.mean(X[self.columns], axis=0)
        self.var_ = np.var(X[self.columns], axis = 0)
        return self
    
    # the transform method which does the actual scaling

    def transform(self, X, y=None, copy=None):
        
        # record the initial order of the columns
        init_col_order = X.columns
        
        # scale all features that you chose when creating the instance of the class
        X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]), columns=self.columns, index=X.index)
        
        # declare a variable containing all information that was not scaled
        X_not_scaled = X.loc[:,~X.columns.isin(self.columns)]
        
        # return a data frame which contains all scaled features and all 'not scaled' features
        # use the original order (that you recorded in the beginning)
        return pd.concat([X_not_scaled, X_scaled], axis=1)[init_col_order]

In [18]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [19]:
#columns_to_scale = ['Month Value', 'Day of the week', 'Transportation Expense', 'Distance to Work',
       #'Age', 'Daily Work Load Average', 'Body Mass Index','Children', 'Pets']
    
columns_to_omit = ['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Education']

In [20]:
columns_to_scale = [x for x in unscaled_inputs.columns.values if x not in columns_to_omit]

In [21]:
absenteeism_scaler = CustomScaler(columns_to_scale)

In [22]:
absenteeism_scaler.fit(unscaled_inputs)
# doing this:
# Whenever you get new data, you will know that the standardization information is contained in the absenteeism_scaler. 
#Thus, we will be able to standardize the new data in the same way.

CustomScaler(columns=['Month Value', 'Transportation Expense', 'Age',
                      'Body Mass Index', 'Children', 'Pets'])

In [23]:
scaled_inputs = absenteeism_scaler.transform(unscaled_inputs)

In [24]:
scaled_inputs

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0           0         0         0         1     0.182726   
1           0         0         0         0     0.182726   
2           0         0         0         1     0.182726   
3           1         0         0         0     0.182726   
4           0         0         0         1     0.182726   
..        ...       ...       ...       ...          ...   
695         1         0         0         0    -0.388293   
696         1         0         0         0    -0.388293   
697         1         0         0         0    -0.388293   
698         0         0         0         1    -0.388293   
699         0         0         0         1    -0.388293   

     Transportation Expense       Age  Body Mass Index  Education  Children  \
0                  1.005844 -0.536062         0.767431          0  0.880469   
1                 -1.574681  2.130803         1.002633          0 -0.019280   
2                 -0.654143  0.248310         1.002633          0 -0.919030   
3                  0.854936  0.405184        -0.643782          0  0.880469   
4                  1.005844 -0.536062         0.767431          0  0.880469   
..                      ...       ...              ...        ...       ...   
695               -0.654143  0.562059        -1.114186          1  0.880469   
696                0.040034 -1.320435        -0.643782          0 -0.019280   
697                1.624567 -1.320435        -0.408580          1 -0.919030   
698                0.190942 -0.692937        -0.408580          1 -0.919030   
699                1.036026  0.562059        -0.408580          0 -0.019280   

         Pets  
0    0.268487  
1   -0.589690  
2   -0.589690  
3   -0.589690  
4    0.268487  
..        ...  
695 -0.589690  
696  1.126663  
697 -0.589690  
698 -0.589690  
699  0.268487  

[700 rows x 11 columns]

In [25]:
scaled_inputs.shape

(700, 11)

#### Split the data into train and test and shuffle

In [26]:
from sklearn.model_selection import train_test_split

#### Split

In [27]:
# default is 75 , 25 split
x_train, x_test, y_train, y_test = train_test_split(scaled_inputs, targets, train_size = 0.8, random_state=42)

In [28]:
print(x_train.shape, y_train.shape)

(560, 11) (560,)


In [29]:
print(x_test.shape, y_test.shape)

(140, 11) (140,)


### Logisctic Regression with sklearn

In [30]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

#### Training the model

In [31]:
reg = LogisticRegression()

In [32]:
reg.fit(x_train, y_train)

LogisticRegression()

In [33]:
reg.score(x_train, y_train)

0.7732142857142857

#### Manually check the accuracy

In [34]:
model_outputs = reg.predict(x_train)
model_outputs

array([1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1,
       1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0,

In [35]:
y_train

array([1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0,

In [36]:
model_outputs == y_train

array([ True,  True,  True,  True, False, False, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True,  True,  True,  True, False,  True,  True,  True,
        True, False, False,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True, False,  True, False,  True,
        True, False, False,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False, False,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True, False, False,  True,
        True,  True, False,  True,  True, False,  True,  True,  True,
        True,  True, False,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,

In [37]:
np.sum(model_outputs == y_train)

433

In [38]:
# Accuracy = Correct predictions/ number of observations
model_outputs.shape[0]

560

In [39]:
np.sum((model_outputs == y_train)) / model_outputs.shape[0]

0.7732142857142857

#### Finding the intercept and coefficients

In [40]:
reg.intercept_

array([-1.70293007])

In [41]:
reg.coef_

array([[ 2.9136209 ,  0.75484748,  3.09891742,  0.96486444,  0.07441017,
         0.65018629, -0.25112372,  0.25250206, -0.24004052,  0.39910996,
        -0.29389223]])

In [42]:
# Whenever we employ sklearn(usually) the results are arrays, not data frames
# scaled_inputs.columns.values

In [43]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [44]:
feature_name = unscaled_inputs.columns.values

In [45]:
summary_table = pd.DataFrame(columns=['Feature name'], data = feature_name)
summary_table['Coefficient'] = np.transpose(reg.coef_)
summary_table

Feature name  Coefficient
0                 Reason_1     2.913621
1                 Reason_2     0.754847
2                 Reason_3     3.098917
3                 Reason_4     0.964864
4              Month Value     0.074410
5   Transportation Expense     0.650186
6                      Age    -0.251124
7          Body Mass Index     0.252502
8                Education    -0.240041
9                 Children     0.399110
10                    Pets    -0.293892

In [46]:
summary_table.index = summary_table.index+1
summary_table.loc[0] = ['Intercept', reg.intercept_[0]]
summary_table = summary_table.sort_index()
summary_table

Feature name  Coefficient
0                Intercept    -1.702930
1                 Reason_1     2.913621
2                 Reason_2     0.754847
3                 Reason_3     3.098917
4                 Reason_4     0.964864
5              Month Value     0.074410
6   Transportation Expense     0.650186
7                      Age    -0.251124
8          Body Mass Index     0.252502
9                Education    -0.240041
10                Children     0.399110
11                    Pets    -0.293892

#### Interpreting the coefficients

In [47]:
# the closer the weight/coefficient to 0, the smaller the weight.
# alternatively the further away from 0, no matter positive or negative, the bigger the weight of this feature
# this holds only for models where all variables are of the same scale
# whenever the scale is standard or the same, that is, we can simply say, whichever weight is bigger, its corresponding feature is more important.
# whenever we are dealing with a logistic regression, the coefficients we are predicting are the so-called log odds.
# Logistic regressions, by default, are nothing but a linear function predicting log odds.

In [48]:
summary_table['Odds_ratio'] = np.exp(summary_table.Coefficient)

In [49]:
summary_table

Feature name  Coefficient  Odds_ratio
0                Intercept    -1.702930    0.182149
1                 Reason_1     2.913621   18.423387
2                 Reason_2     0.754847    2.127287
3                 Reason_3     3.098917   22.173933
4                 Reason_4     0.964864    2.624432
5              Month Value     0.074410    1.077249
6   Transportation Expense     0.650186    1.915898
7                      Age    -0.251124    0.777926
8          Body Mass Index     0.252502    1.287242
9                Education    -0.240041    0.786596
10                Children     0.399110    1.490498
11                    Pets    -0.293892    0.745357

In [50]:
summary_table.sort_values('Odds_ratio', ascending=False)

Feature name  Coefficient  Odds_ratio
3                 Reason_3     3.098917   22.173933
1                 Reason_1     2.913621   18.423387
4                 Reason_4     0.964864    2.624432
2                 Reason_2     0.754847    2.127287
6   Transportation Expense     0.650186    1.915898
10                Children     0.399110    1.490498
8          Body Mass Index     0.252502    1.287242
5              Month Value     0.074410    1.077249
9                Education    -0.240041    0.786596
7                      Age    -0.251124    0.777926
11                    Pets    -0.293892    0.745357
0                Intercept    -1.702930    0.182149

In [51]:
#If a coefficient is around zero or its odds ratio is close to one, this means that the corresponding feature is not particularly important.
#For one unit change in the standardized feature, the odds increase by a multiple equal to the odds ratio.
#So if the odds ratio is one, then the odds don't change at all.
#For example, if the odds are five to one and the odds ratio is two, we would say that for one unit change, the odds change from five to one
#to 10 to one
#because we multiply them by the odds ratio.
#Alternatively, if the odds ratio is 0.2, the odds ratio would change to one to one. 
#When the odds ratio is one, we don't have a change as multiplication with the number one keeps things equal.

In [52]:
# A feature is not particularly important:
# --> if its coefficient is around 0
# --> if its odds ratio is around 1

In [53]:
# When we standardized the inputs we also standardized the dummies.
#This is bad practice because when we standardize we lose the whole interpretability of a dummy.
#If we had left them as zeros and ones, we could have said, for a unit change it is 7.2 times more likely that a person will be excessively absent.

#So if the reason is reason one, we would've said it is around seven times more likely that a person will be absent compared to no reason given. However, we standardized the reasons and now a unit change is completely uninterpretable.

#The predictive power of the model is still valid and it is a good classifier but we don't know how the different reasons compare.

In [54]:
# The futher way from 0 a coefficient is, the bigger its importance
# Reason 0 = No reason = baseline model (when no reason is given)
summary_table.sort_values('Odds_ratio', ascending=False)
#without an Intercept, each prediction would be off the mark by precisely that value.

Feature name  Coefficient  Odds_ratio
3                 Reason_3     3.098917   22.173933
1                 Reason_1     2.913621   18.423387
4                 Reason_4     0.964864    2.624432
2                 Reason_2     0.754847    2.127287
6   Transportation Expense     0.650186    1.915898
10                Children     0.399110    1.490498
8          Body Mass Index     0.252502    1.287242
5              Month Value     0.074410    1.077249
9                Education    -0.240041    0.786596
7                      Age    -0.251124    0.777926
11                    Pets    -0.293892    0.745357
0                Intercept    -1.702930    0.182149

#### Testing the mode;

In [55]:
reg.score(x_test, y_test)

0.7714285714285715

In [56]:
predicted_proba = reg.predict_proba(x_test)

In [57]:
#if prob is < 0.5 --> 0; prob is > 0.5 --> 1 
predicted_proba

array([[0.82957126, 0.17042874],
       [0.85163998, 0.14836002],
       [0.79779583, 0.20220417],
       [0.593212  , 0.406788  ],
       [0.57365867, 0.42634133],
       [0.08041824, 0.91958176],
       [0.67595129, 0.32404871],
       [0.35568421, 0.64431579],
       [0.7163203 , 0.2836797 ],
       [0.74005176, 0.25994824],
       [0.86456635, 0.13543365],
       [0.67492732, 0.32507268],
       [0.26570587, 0.73429413],
       [0.44925745, 0.55074255],
       [0.72600362, 0.27399638],
       [0.4921817 , 0.5078183 ],
       [0.89459595, 0.10540405],
       [0.21441612, 0.78558388],
       [0.86703473, 0.13296527],
       [0.58401659, 0.41598341],
       [0.73026575, 0.26973425],
       [0.74411785, 0.25588215],
       [0.68178599, 0.31821401],
       [0.67957102, 0.32042898],
       [0.86082189, 0.13917811],
       [0.16084394, 0.83915606],
       [0.59430082, 0.40569918],
       [0.59675531, 0.40324469],
       [0.75996029, 0.24003971],
       [0.59941268, 0.40058732],
       [0.

In [58]:
predicted_proba.shape

(140, 2)

In [59]:
predicted_proba[:, 1]

array([0.17042874, 0.14836002, 0.20220417, 0.406788  , 0.42634133,
       0.91958176, 0.32404871, 0.64431579, 0.2836797 , 0.25994824,
       0.13543365, 0.32507268, 0.73429413, 0.55074255, 0.27399638,
       0.5078183 , 0.10540405, 0.78558388, 0.13296527, 0.41598341,
       0.26973425, 0.25588215, 0.31821401, 0.32042898, 0.13917811,
       0.83915606, 0.40569918, 0.40324469, 0.24003971, 0.40058732,
       0.11740629, 0.14127068, 0.59939433, 0.56123137, 0.27824269,
       0.64991631, 0.31821401, 0.13371416, 0.85473685, 0.19918143,
       0.518433  , 0.25185802, 0.63451971, 0.12814276, 0.2248817 ,
       0.72597901, 0.76889861, 0.88389353, 0.30906773, 0.13053509,
       0.25994824, 0.31362277, 0.42634133, 0.93283814, 0.13871298,
       0.2248817 , 0.97636259, 0.27824269, 0.87185363, 0.22500107,
       0.59270754, 0.11962568, 0.49902329, 0.64431579, 0.13543365,
       0.41351   , 0.68000722, 0.05803086, 0.26979066, 0.50509959,
       0.25994824, 0.24003971, 0.69828514, 0.31362277, 0.13416

#### Save the model

In [60]:
#pickle[module] is a Python module used to convert a Python object into a character stream
import pickle

In [61]:
with open('model', 'wb') as file: #'model' --> filename; 'wb' --> write bytes
    pickle.dump(reg, file) #dump --> save; dump reg 

In [62]:
# pickle the scaler file
with open('scaler','wb') as file:
    pickle.dump(absenteeism_scaler, file)